swagger: '2.0'
info:
  title: IP Route API
  description: Handle the routing table
  version: "1.0.0"

schemes:
- http
- https
produces:
- application/json
paths:
  /network/routes/default:
    get:
      summary: Current Default Route and priority list
      description: |
        The system returns the current default route information and default
        route priority list.
      responses:
        200:
          description: Default Route
          schema:
            $ref: '#/definitions/DefaultRoute'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/DefaultRoute'
              }
            }
    put:
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/DefaultRoute'
      summary: Update Default Route Setting
      description: Update the default route list.
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/DefaultRoute'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/DefaultRoute_Put'
              }
            }

definitions:
  DefaultRoute:
    title: DefaultRoute
    required:
    - interface
    properties:
      interface:
        type: string
        readOnly: true
        description: Indicate the interface name.
      gateway:
        type: string
        pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
        readOnly: true
        description: |
          Gateway is a router or a proxy server that routes between networks.
      priorityList:
        type: array
        items:
          description: interface for default route
          type: string
          pattern: '[A-Za-z0-9_-]+'
          minLength: 2
          maxLength: 255
    example:
          $ref: '#/externalDocs/x-mocks/DefaultRoute'

externalDocs:
  url: '#'
  x-mocks:
    DefaultRoute:
      {
        "interface": "eth0",
        "gateway": "192.168.3.254",
        "priorityList": ["wwan0", "eth0"]
      }
    DefaultRoute_Put:
      {
        "priorityList": ["wwan0", "eth0"]
      }
